apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
  labels:
    app: canary
spec:
  replicas: 1  # Número de réplicas para la versión canary
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary
        image: tu-imagen-canary:latest  # Reemplaza con tu imagen canary
        ports:
        - containerPort: 80  # Puerto expuesto