apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-deployment
  labels:
    app: stable
spec:
  replicas: 3  # Número de réplicas
  selector:
    matchLabels:
      app: stable
  template:
    metadata:
      labels:
        app: stable
    spec:
      containers:
      - name: stable
        image: tu-imagen-stable:latest  # Reemplaza con tu imagen
        ports:
        - containerPort: 80  # Puerto expuesto
